Traceback (most recent call last):
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 87, in get_gd_pymoo
    front = problem_.pareto_front()
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/util/cache.py", line 22, in wrapper
    obj = func(self, *args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/core/problem.py", line 385, in pareto_front
    pf = self._calc_pareto_front(*args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/many/dtlz.py", line 125, in _calc_pareto_front
    raise Exception("Not implemented yet.")
Exception: Not implemented yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 237, in <module>
    gd = get_gd_pymoo(non_dom_solutions, problem)
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 91, in get_gd_pymoo
    front = np.loadtxt("./pf/" + pf_file_name)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./pf/<BOUND METHOD PROBLEM.NAME OF <PYMOO.PROBLEMS.MANY.DTLZ.DTLZ5 OBJECT AT 0X7F5CCD8F2460>>.2D.PF not found.
2023-12-05 16:07:22 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205160722_2912 > exp/20231205160722_2912/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205160722_2912/output.txt
Traceback (most recent call last):
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 87, in get_gd_pymoo
    front = problem_.pareto_front()
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/util/cache.py", line 22, in wrapper
    obj = func(self, *args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/core/problem.py", line 385, in pareto_front
    pf = self._calc_pareto_front(*args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/many/dtlz.py", line 125, in _calc_pareto_front
    raise Exception("Not implemented yet.")
Exception: Not implemented yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 237, in <module>
    gd = get_gd_pymoo(non_dom_solutions, problem)
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 91, in get_gd_pymoo
    front = np.loadtxt("./pf/" + pf_file_name)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./pf/<BOUND METHOD PROBLEM.NAME OF <PYMOO.PROBLEMS.MANY.DTLZ.DTLZ5 OBJECT AT 0X7F250113BC70>>.2D.PF not found.
2023-12-05 16:10:44 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205161044_7499 > exp/20231205161044_7499/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205161044_7499/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 237, in <module>
    gd = get_gd_pymoo(non_dom_solutions, problem)
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 93, in get_gd_pymoo
    return compute_gd(obj_values, front)
UnboundLocalError: local variable 'obj_values' referenced before assignment
2023-12-05 16:13:57 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205161357_10936 > exp/20231205161357_10936/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205161357_10936/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 303, in <module>
    front = _problem.pareto_front()
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/util/cache.py", line 22, in wrapper
    obj = func(self, *args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/core/problem.py", line 385, in pareto_front
    pf = self._calc_pareto_front(*args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/many/dtlz.py", line 125, in _calc_pareto_front
    raise Exception("Not implemented yet.")
Exception: Not implemented yet.
2023-12-05 16:22:37 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205162237_2112 > exp/20231205162237_2112/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205162237_2112/output.txt
2023-12-05 16:27:00 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205162700_7858 > exp/20231205162700_7858/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205162700_7858/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 223, in <module>
    archive, archive_arr = scalar_dom_ea_dp_2(INIT_SIZE, toolbox, MU, LAMBDA, MAX_EVALUATIONS, category_size=CATEGORY_SIZE, rate=RATE, strategy=STRATEGY)
  File "/home/robin/projects/tdeadp-master/evolution/multi_tdeadp_2.py", line 23, in scalar_dom_ea_dp
    full_evaluate(pop, toolbox, f_min, f_max)     # evaluate all the solutions in the initial population
  File "/home/robin/projects/tdeadp-master/evolution/utils.py", line 10, in full_evaluate
    fitness_values = toolbox.evaluate(individuals)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/core/problem.py", line 257, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/core/problem.py", line 299, in do
    self._evaluate_vectorized(X, out, *args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/core/problem.py", line 307, in _evaluate_vectorized
    self._evaluate(X, out, *args, **kwargs)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/many/dtlz.py", line 128, in _evaluate
    X_, X_M = x[:, :self.n_obj - 1], x[:, self.n_obj - 1:]
TypeError: list indices must be integers or slices, not tuple
2023-12-05 16:43:04 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205164304_25491 > exp/20231205164304_25491/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205164304_25491/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 223, in <module>
    archive, archive_arr = scalar_dom_ea_dp_2(INIT_SIZE, toolbox, MU, LAMBDA, MAX_EVALUATIONS, category_size=CATEGORY_SIZE, rate=RATE, strategy=STRATEGY)
  File "/home/robin/projects/tdeadp-master/evolution/multi_tdeadp_2.py", line 70, in scalar_dom_ea_dp
    individual = toolbox.filter(offsprings, rep_individuals, nd_rep_individuals, p_model, s_model, category_size, evalTimes=evaluations)      
  File "/home/robin/projects/tdeadp-master/evolution/selection.py", line 63, in pareto_scalar_nn_filter
    visualize_preselection(cid, ref_points, s_rep_ind, list(rep_individuals.values()),
  File "/home/robin/projects/tdeadp-master/evolution/visualizer.py", line 55, in visualize_preselection
    plt.scatter(bv[0], bv[1], marker='o', linewidths=5, c='r')
IndexError: index 1 is out of bounds for axis 0 with size 1
2023-12-05 16:57:04 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205165704_18504 > exp/20231205165704_18504/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205165704_18504/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 285, in <module>
    igd_arr.append(get_igd_pymoo(sln, problem))
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 69, in get_igd_pymoo
    front = get_pareto_front(problem_)
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 172, in get_pareto_front
    problem_ = get_problem(problem.name, n_var=problem.n_var, n_obj=problem.n_obj)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/__init__.py", line 3, in get_problem
    name = name.lower()
AttributeError: 'function' object has no attribute 'lower'
2023-12-05 17:01:40 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205170140_13774 > exp/20231205170140_13774/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205170140_13774/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 285, in <module>
    igd_arr.append(get_igd_pymoo(sln, problem))
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 69, in get_igd_pymoo
    front = get_pareto_front(problem_)
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 174, in get_pareto_front
    problem_ = get_problem(str(problem.name), n_var=problem.n_var, n_obj=problem.n_obj)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/__init__.py", line 155, in get_problem
    raise Exception("Problem not found.")
Exception: Problem not found.
2023-12-05 17:05:14 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205170514_19632 > exp/20231205170514_19632/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205170514_19632/output.txt
2023-12-05 17:06:06 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205170606_8856 > exp/20231205170606_8856/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205170606_8856/output.txt
Traceback (most recent call last):
  File "multi_tdeadp_main_2.py", line 288, in <module>
    igd_arr.append(get_igd_pymoo(sln, problem))
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 69, in get_igd_pymoo
    front = get_pareto_front(problem_)
  File "/home/robin/projects/tdeadp-master/problems/metrics.py", line 174, in get_pareto_front
    problem_ = get_problem(str(problem.name), n_var=problem.n_var, n_obj=problem.n_obj)
  File "/home/robin/anaconda3/envs/tdeadp/lib/python3.8/site-packages/pymoo/problems/__init__.py", line 155, in get_problem
    raise Exception("Problem not found.")
Exception: Problem not found.
2023-12-05 17:09:00 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205170900_3681 > exp/20231205170900_3681/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205170900_3681/output.txt
2023-12-05 17:13:25 python multi_tdeadp_main_2.py --n_obj=2 --n_var=2 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz6 --id=20231205171325_9889 > exp/20231205171325_9889/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205171325_9889/output.txt
2023-12-05 17:16:46 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz1 --id=20231205171646_11998 > exp/20231205171646_11998/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205171646_11998/output.txt
2023-12-05 17:18:25 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz2 --id=20231205171825_5550 > exp/20231205171825_5550/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205171825_5550/output.txt
2023-12-05 17:20:09 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz3 --id=20231205172009_16528 > exp/20231205172009_16528/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205172009_16528/output.txt
2023-12-05 17:22:07 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz4 --id=20231205172207_25715 > exp/20231205172207_25715/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205172207_25715/output.txt
2023-12-05 17:23:50 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz5 --id=20231205172350_5692 > exp/20231205172350_5692/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205172350_5692/output.txt
2023-12-05 17:25:24 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz6 --id=20231205172524_745 > exp/20231205172524_745/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205172524_745/output.txt
2023-12-05 17:27:11 python multi_tdeadp_main_2.py --n_obj=3 --n_var=3 --alg=2 --rate=0.5 --strategy=2 --max_fe=50 --problem=dtlz7 --id=20231205172711_8037 > exp/20231205172711_8037/output.txt 2> >(tee -a log.txt >&2) >> exp/20231205172711_8037/output.txt
